export TARGET = iphone:latest:12.0

FRAMEWORK_OUTPUT_DIR = $(THEOS_OBJ_DIR)/xcode_derived/install/Library/Frameworks
export ADDITIONAL_CFLAGS = -fobjc-arc -Wextra -Wno-unused-parameter -F$(FRAMEWORK_OUTPUT_DIR)
export ADDITIONAL_LDFLAGS = -F$(FRAMEWORK_OUTPUT_DIR)

INSTALL_TARGET_PROCESSES = Preferences

include $(THEOS)/makefiles/common.mk

XCODEPROJ_NAME = Alderis

Alderis_XCODEFLAGS = DYLIB_INSTALL_NAME_BASE=/Library/Frameworks

include $(THEOS_MAKE_PATH)/xcodeproj.mk

internal-Alderis-stage::
	@# Copy postinst
	@mkdir -p $(THEOS_STAGING_DIR)/DEBIAN
	@cp postinst $(THEOS_STAGING_DIR)/DEBIAN

	@# Remove noisy files generated by Xcode
	@rm -r $(THEOS_STAGING_DIR)/Library/Frameworks/Alderis.framework/{Headers,Modules}
